### ISSUE TITLE
No need for dummy methods like `expressionNode()`

### ISSUE THREAD

**Issue by orkhan-huseyn** [zhuzilin/monkey#1]
In GoLang interfaces are implemented implicitly, meaning that there is no way to say `IfExpression implements Expression` that is why you need to implement one of its methods `expressionNode()` to say that this `struct` implements `Expression` interface. In C++ you don't need that, just saying `class IfExpression : public Expression ... ` is enough, I believe.

**Comment by orkhan-huseyn** [comment]
This is also true for `TokenLiteral()` method unless you decide to encapsulate `TokenLiteral` instance variable.

**Comment by zhuzilin** [comment]
@orkhan-huseyn 
You are absolutely right... I guess I was blindly copy the Go code without understanding it. Thank you for your advice and I've changed it with commit 4ce753770f80.
